version: "3"
services:
  app:
    container_name: driver_microservice
    build: "."
    ports:
      - 5003:5000
    restart: always
    depends_on:
      - driver-mongo
    networks:
      - fiuber-network

  driver-mongo:
    container_name: traveldb_microservice
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: prueba
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fiuber-network

networks:
  fiuber-network:
    driver: bridge
    name: fiuber-network
