version: "3"
services:
  app:
    container_name: travel_microservice
    build: "."
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5003:5000
    restart: always
    depends_on:
      - mongo
    networks:
      - fiuber-network

  mongo:
    container_name: traveldb_microservice
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - fiuber-network
volumes:
  mongodb:


networks:
  fiuber-network:
    driver: bridge
    name: fiuber-network
